server:
  port: 8081

name: 土豪
age: 40
content: "name:${name},age:${age}}"

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_jojoya
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true